### PR TITLE
Changes by Diego

### PR DESCRIPTION
**Pull request by Diegotab**
Hi guys! 

First of all, I think that you have made a great job at making use of the descriptive statistics that we covered in class. I have only added a couple of titles for some graphs as well as the code chunk to get png files for each of the graphs you created. Moreover, when it comes to the measures of dispersion, I have also added a loop to calculate the variance. 

On the other hand, I think that you offer really good interpretations of the statistics that you use. Nevertheless, you have multiple markdown and readme documents. It would probably be easier to follow if you combine everything in one markdown document (this is just a suggestion, of course you can do however you think it is best). 

Best,
Diego

### CODE REVIEW

**Comment by jmarkgraf** [comment]
Thanks, Diego, for your comments and the pull request. Regarding the png exports, I would argue that we don't really need them as we present the graphs in the single Markdown for Life Cycle Savings. I however agree that the files look a bit messy at the moment. @mberneaud: Let's try to give consistent names to the files.

**Comment by mberneaud** [comment]
@jmarkgraf : Which file names do you mean specifically? As for the code on the graphs: there's a tool which you can use to pick-and-choose which changes to merge into our repo, I'm sure.

**Comment by Diegotab** [comment]
Yes! It is true that you already present the graphs in the single Markdown for Life Cycle Savings. Isabelle and I decided to go for just one markdown document in which we covered our two datasets. 

Apart from that, there's not much more that I could have added since you used pretty much all the descriptive statistics. I only added one more loop to calculate the variance.

**Comment by mberneaud** [comment]
Alright, I did the merge now as suggested by @jmarkgraf, which means were done here! Yay! Thanks for collaborating, @Diegotab  and @imiller88.

**Pull request merged**
